package com.fabri.ministerium;

import android.content.Context;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.text.Normalizer;
import java.util.Locale;

/**
 * Read-only access to the structured Mercabá package generated by
 * tools/import_mercaba_missal.py.
 *
 * Safety rule: an entry is NEVER returned to the live Missal unless it was
 * explicitly marked verifiedForEcuador=true during the build/review process.
 * This prevents an older Latin-American translation from silently overriding
 * the Ecuador-approved Missal.
 */
public final class MercabaMissalRepository {
    private static final String ASSET = "missal/mercaba/index.json";

    public static final class Match {
        public final String id;
        public final String title;
        public final String text;
        public final String sourceUrl;
        public final String sourceEdition;

        Match(String id, String title, String text, String sourceUrl, String sourceEdition) {
            this.id = value(id);
            this.title = value(title);
            this.text = value(text);
            this.sourceUrl = value(sourceUrl);
            this.sourceEdition = value(sourceEdition);
        }
    }

    private MercabaMissalRepository() {}

    public static Match verifiedProper(Context context, String celebration, String part) {
        if (context == null || value(celebration).isEmpty() || value(part).isEmpty()) return null;
        try {
            JSONObject root = readPackage(context);
            if (root.optInt("schemaVersion", 0) != 1) return null;
            JSONArray entries = root.optJSONArray("entries");
            if (entries == null) return null;
            String target = normalize(celebration);
            Match best = null;
            int bestScore = 0;
            for (int i = 0; i < entries.length(); i++) {
                JSONObject entry = entries.optJSONObject(i);
                if (entry == null || !entry.optBoolean("verifiedForEcuador", false)) continue;
                JSONObject parts = entry.optJSONObject("parts");
                if (parts == null) continue;
                String text = value(parts.optString(part));
                if (text.isEmpty()) continue;
                String title = value(entry.optString("title"));
                int score = score(target, normalize(title));
                if (score > bestScore) {
                    bestScore = score;
                    best = new Match(entry.optString("id"), title, text,
                            entry.optString("sourceUrl"), entry.optString("sourceEdition"));
                }
            }
            // Avoid fuzzy accidents between adjacent saints/formularies.
            return bestScore >= 86 ? best : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    public static boolean hasVerifiedContent(Context context) {
        try {
            JSONArray entries = readPackage(context).optJSONArray("entries");
            if (entries == null) return false;
            for (int i = 0; i < entries.length(); i++) {
                JSONObject entry = entries.optJSONObject(i);
                if (entry != null && entry.optBoolean("verifiedForEcuador", false)) return true;
            }
        } catch (Exception ignored) {}
        return false;
    }

    public static String render(Match match) {
        if (match == null || match.text.isEmpty()) return "";
        StringBuilder html = new StringBuilder();
        html.append("<div class=\"daily-proper mercaba-proper\" data-missal-source=\"mercaba\">")
                .append("<div class=\"proper-language-note\">Respaldo verificado · Mercabá</div>");
        for (String paragraph : match.text.split("\\n\\s*\\n")) {
            String value = paragraph.trim();
            if (!value.isEmpty()) html.append("<p>").append(escape(value).replace("\n", "<br>"))
                    .append("</p>");
        }
        return html.append("</div>").toString();
    }

    private static JSONObject readPackage(Context context) throws Exception {
        try (InputStream input = context.getAssets().open(ASSET);
             ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[8192];
            int count;
            while ((count = input.read(buffer)) != -1) output.write(buffer, 0, count);
            return new JSONObject(new String(output.toByteArray(), StandardCharsets.UTF_8));
        }
    }

    private static int score(String a, String b) {
        if (a.equals(b)) return 100;
        if (a.isEmpty() || b.isEmpty()) return 0;
        if (a.contains(b) || b.contains(a)) {
            int shorter = Math.min(a.length(), b.length());
            int longer = Math.max(a.length(), b.length());
            return 88 + (int) Math.round(10d * shorter / Math.max(1, longer));
        }
        String[] aa = a.split(" ");
        String[] bb = b.split(" ");
        int common = 0;
        for (String left : aa) {
            if (left.length() < 3) continue;
            for (String right : bb) {
                if (left.equals(right)) { common++; break; }
            }
        }
        int base = Math.max(aa.length, bb.length);
        return base == 0 ? 0 : (int) Math.round(85d * common / base);
    }

    private static String normalize(String input) {
        String value = Normalizer.normalize(value(input), Normalizer.Form.NFD)
                .replaceAll("\\p{M}+", "")
                .toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9 ]+", " ")
                .replaceAll("\\s+", " ").trim();
        return value.replaceAll("\\b(memoria|solemnidad|fiesta|doctor de la iglesia|obispo|presbitero|martir|virgen)\\b", " ")
                .replaceAll("\\s+", " ").trim();
    }

    private static String value(String value) {
        return value == null ? "" : value.trim();
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }
}
